<?php

/**
 * @file
 * Implementaiton of the security.txt standard for backdrop.
 *
 * @see https://securitytxt.org/
 */

/**
 * Implements hook_menu().
 */
function securitytxt_menu() {
    $items['admin/config/system/securitytxt'] = array(
        'title' => 'Security.txt',
        'description' => 'Configure and sign the site security.txt file.',
        'page callback' => 'backdrop_get_form',
        'page arguments' => array('securitytxt_file_form'),
        'access arguments' => array('administer securitytxt'),
        'file' => 'securitytxt.admin.inc',
        'weight' => 50,
    );

    $items['admin/config/system/securitytxt/file'] = array(
        'title' => 'Configure',
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    $items['admin/config/system/securitytxt/sign'] = array(
        'title' => 'Sign',
        'page callback' => 'backdrop_get_form',
        'page arguments' => array('securitytxt_sign_form'),
        'access arguments' => array('administer securitytxt'),
        'file' => 'securitytxt.admin.inc',
        'type' => MENU_LOCAL_TASK,
    );

    $items['.well-known/security.txt'] = array(
        'title' => 'Security.txt file',
        'page callback' => 'securitytxt_file_page',
        'access arguments' => array('view securitytxt'),
        'file' => 'securitytxt.pages.inc',
        'type' => MENU_CALLBACK,
    );

    $items['.well-known/security.txt.sig'] = array(
        'title' => 'Security.txt file signature',
        'page callback' => 'securitytxt_signature_page',
        'access arguments' => array('view securitytxt'),
        'file' => 'securitytxt.pages.inc',
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_permission().
 */
function securitytxt_permission() {
    return array(
        'administer securitytxt' => array(
            'title' => t('Administer security.txt'),
            'description' => t('Allows configuring and signing of the security.txt file.'),
            'restrict access' => TRUE,
        ),
        'view securitytxt' => array(
            'title' => t('View security.txt'),
            'description' => t('Allows access to the security.txt and security.txt.sig files. You will almost certinaly want to grant this permission to both the Anonymous and Authenticated user roles.'),
        ),
    );
}
